import Link from "next/link";
// import { Metadata } from 'next'

// If using Next version later than 13.0.6
// export const metadata: Metadata = {
//     title: 'About page',
//     description: 'Generated by create next app',
// }

export default function About() {
  return (
    <>
      <h1>About</h1>
      <Link href="/">Link to home page</Link>
    </>
  );
}
